services:
  postgres:
    image: postgres:16
    container_name: clinicaN
    environment:
      POSTGRES_DB: clinicaN
      POSTGRES_USER: clinica123
      POSTGRES_PASSWORD: clinica123
    ports:
      - "5432:5432"
    volumes:
      - crud_data:/var/lib/postgresql/data

volumes:
  crud_data: